### ISSUE TITLE
FYI - react-app-rewired 'rewires'

### ISSUE THREAD

**Issue by timarney** [thtliife/pluggable-plugin-template#1]
Hi @thtliife 

Found your project from the notifications for the CRA repo.

Not sure if you've seen this repo https://github.com/timarney/react-app-rewired (not a fork, just gets access to the configs) .  I could be wrong but seems to be along the same lines as to what your doing.

Just noting this as it 'might' make sense if your following the same override signature for 'pluggables'

The rewires here -> https://github.com/timarney/react-app-rewired/tree/master/packages 

Follow this pattern

```javascript
/* config-overrides.js */
module.exports = function override(config, env) {
  //do stuff with the webpack config...
  return config;
}
```

Will have another one on the way soon https://github.com/timarney/react-app-rewired/issues/22 .

Anyway just putting that out there to see what you think.  Enjoy the plugging.

**Comment by thtliife** [comment]
Hi @timarney 
Wow, its amazing how similar a method i have used to yours. :)
The only real differences that i can see are my method of detecting plugins from the cra package.json, and autowrapping them.
I did that because i wanted the "pluggables" to be enabled by simply `npm install --save / --save-dev` with no other config...

Hopefully that might allow other people to release "pluggables" via npm. (My idea was much like yours from https://github.com/timarney/react-app-rewired/issues/22.)

> Personally I would like to see people adding 'rewires' to npm and I can link / point people to them from this repo.

Otherwise the pattern is almost identical...

Might be worth thinking about retiring my cra fork and contibuting to react-app-rewired instead... ?

**Comment by timarney** [comment]
I do like the idea of having everything auto setup but at this point I for one am still discovering how these types of things can / will be used in common practice i.e. https://github.com/timarney/cra-mobx-reactrouter/blob/master/config-overrides.js given access to the config I can modify per app as needed in this case flip to Preact for use in production to trim the filesize.  

Seems maybe a blend of auto / manual is best.  Easy to use but able to tweak as needed.  Happy to explore auto further.

I would be happy to see you contribute to react-app-rewired mainly thinking the pluggables / rewires could play well together.

Also note: react-app-rewired works with forked versions of react custom scripts so that's kind of fun as well.
